foreach(var COMPILED_SCRIPTS OUTPUT_FOLDER)
    if(NOT DEFINED ${var})
        message(FATAL_ERROR "Required variable ${var} was not provided to CopyScripts.cmake")
    endif()
endforeach()

string(REGEX REPLACE "^\"|\"$" "" COMPILED_SCRIPTS "${COMPILED_SCRIPTS}")
string(REGEX REPLACE "^\"|\"$" "" OUTPUT_FOLDER "${OUTPUT_FOLDER}")
file(TO_CMAKE_PATH "${COMPILED_SCRIPTS}" COMPILED_SCRIPTS)
file(TO_CMAKE_PATH "${OUTPUT_FOLDER}" OUTPUT_FOLDER)

if(EXISTS "${COMPILED_SCRIPTS}" AND IS_DIRECTORY "${COMPILED_SCRIPTS}")
    set(DEST_COMPILED "${OUTPUT_FOLDER}/Scripts")
    message(STATUS "Copying compiled Papyrus scripts from ${COMPILED_SCRIPTS} to ${DEST_COMPILED}")

    if(EXISTS "${DEST_COMPILED}")
        file(REMOVE_RECURSE "${DEST_COMPILED}")
    endif()
    file(MAKE_DIRECTORY "${DEST_COMPILED}")
    file(GLOB COMPILED_ITEMS "${COMPILED_SCRIPTS}/*")
    if(COMPILED_ITEMS)
        foreach(f ${COMPILED_ITEMS})
            get_filename_component(fname "${f}" NAME)
            file(COPY "${f}" DESTINATION "${DEST_COMPILED}/")
        endforeach()
        message(STATUS "Copied ${COMPILED_SCRIPTS} contents to ${DEST_COMPILED}")
    else()
        message(STATUS "No compiled scripts found in ${COMPILED_SCRIPTS}")
    endif()
else()
    message(STATUS "Compiled Papyrus scripts not found at ${COMPILED_SCRIPTS}, skipping.")
endif()