foreach(var SOURCE_SCRIPTS OUTPUT_FOLDER)
    if(NOT DEFINED ${var})
        message(FATAL_ERROR "Required variable ${var} was not provided to CopySources.cmake")
    endif()
endforeach()

string(REGEX REPLACE "^\"|\"$" "" SOURCE_SCRIPTS "${SOURCE_SCRIPTS}")
string(REGEX REPLACE "^\"|\"$" "" OUTPUT_FOLDER "${OUTPUT_FOLDER}")
file(TO_CMAKE_PATH "${SOURCE_SCRIPTS}" SOURCE_SCRIPTS)
file(TO_CMAKE_PATH "${OUTPUT_FOLDER}" OUTPUT_FOLDER)

if(EXISTS "${SOURCE_SCRIPTS}" AND IS_DIRECTORY "${SOURCE_SCRIPTS}")
    set(DEST_SRC "${OUTPUT_FOLDER}/Source/Scripts")
    message(STATUS "Copying Papyrus source scripts from ${SOURCE_SCRIPTS} to ${DEST_SRC}")

    if(EXISTS "${DEST_SRC}")
        file(REMOVE_RECURSE "${DEST_SRC}")
    endif()
    file(MAKE_DIRECTORY "${DEST_SRC}")
    file(GLOB SRC_ITEMS "${SOURCE_SCRIPTS}/*")
    if(SRC_ITEMS)
        foreach(f ${SRC_ITEMS})
            get_filename_component(fname "${f}" NAME)
            file(COPY "${f}" DESTINATION "${DEST_SRC}/")
        endforeach()
        message(STATUS "Copied ${SOURCE_SCRIPTS} contents to ${DEST_SRC}")
    else()
        message(STATUS "No files found in ${SOURCE_SCRIPTS}")
    endif()
else()
    message(STATUS "Papyrus source scripts not found at ${SOURCE_SCRIPTS}, skipping.")
endif()